version: 2.1

jobs:
  lint-dockerfile:
    machine: true
    steps:
      - checkout
      - run:
          name: Install hadolint
          command: curl -s https://raw.githubusercontent.com/hadolint/hadolint/master/install.sh | bash
      - run:
          name: Lint Dockerfile
          command: ./hadolint Dockerfile

  test-app:
    docker:
      - image: golang:1.20
    steps:
      - checkout
      - run:
          name: Run Go Tests
          command: go test -v -short --count=1 $(go list ./...)

  build-app-karsajobs:
    machine: true
    steps:
      - checkout
      - run:
          name: Login GHCR
          command: echo "$GHCR_PAT" | docker login ghcr.io -u "$DOCKER_USERNAME" --password-stdin

      - run:
          name: Build image

